compile: Nett/Test/Nett.TestDecoder/bin/Debug/Nett.TestDecoder.exe

Nett/Test/Nett.TestDecoder/bin/Debug/Nett.TestDecoder.exe:
	brew bundle && \
	msbuild Nett/Test/Nett.TestDecoder/Nett.TestDecoder.csproj

clean:
	cd Nett && \
	git clean -xdf
